spring:
  application:
    name: CRUD
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediasoft_db
    username: postgres
    password: 1

server:
  port: 8080
  servlet.context-path: /
